version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: disease-prediction-api
    container_name: disease-prediction-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - disease-prediction-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: disease-prediction-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - disease-prediction-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: disease-prediction-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: disease_prediction
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: laravel_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - disease-prediction-network

networks:
  disease-prediction-network:
    driver: bridge

volumes:
  dbdata:
    driver: local